version: '3.9'
services:
  nginx:
    container_name: nginx
    build: 
      context: .
      dockerfile: nginx.dockerfile
    ports: 
      - '80:80'
      - '443:443'
    volumes: 
      - ./src:/var/www/html
    networks:
      - laravel
    depends_on:
      - php
      - mysql
  
  #    apache:
  #        build:
  #            context: .
  #            dockerfile: apache.dockerfile
  #        container_name: apache
  #        ports:
  #            - 80:80
  #            - 443:443
  #        volumes:
  #            - ./src:/var/www/html
  #        networks:
  #            - laravel

  
  php:
    container_name: php
    build: 
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel

  mysql:
    container_name: mysql
    image: mysql:8.0.27
    platform: linux/x86_64
    ports: 
      - '3306:3306'
    volumes: 
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laraveldb
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    networks: 
      - laravel

  composer:
    container_name: composer
    image: composer:latest
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - laravel
    
  artisan:
    container_name: artisan
    build: 
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['php', 'artisan']
    networks:
      - laravel

  npm:
    container_name: npm
    image: node:current-alpine
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']
    networks: 
      - laravel

networks:
    laravel:
        name: laravel
